docker_compose_version: "v2.20.3"
docker_compose_exec_path: "/usr/local/bin/docker-compose"
docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
